global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-apps'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'gateway:8080'
          - 'book-service:8081'
          - 'notification-service:8082'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: application
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'

  - job_name: 'zipkin'
    static_configs:
      - targets: ['zipkin:9411']
    metrics_path: /metrics